"""user-profile relationship_v4

Revision ID: 62dec190ee1f
Revises: ab9eb71a1ae5
Create Date: 2026-01-30 17:53:56.309509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62dec190ee1f'
down_revision: Union[str, Sequence[str], None] = 'ab9eb71a1ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
