"""upd UniqueConstraint

Revision ID: e939140b23bd
Revises: 11f9791cb0ca
Create Date: 2026-01-30 04:02:10.485918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e939140b23bd'
down_revision: Union[str, Sequence[str], None] = '11f9791cb0ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('oauth_accounts_provider_id_key'), 'oauth_accounts', type_='unique')
    op.drop_constraint(op.f('oauth_accounts_provider_key'), 'oauth_accounts', type_='unique')
    op.create_unique_constraint('uq_provider_provider_id', 'oauth_accounts', ['provider', 'provider_id'])
    op.create_unique_constraint('uq_user_provider', 'oauth_accounts', ['user_id', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_provider', 'oauth_accounts', type_='unique')
    op.drop_constraint('uq_provider_provider_id', 'oauth_accounts', type_='unique')
    op.create_unique_constraint(op.f('oauth_accounts_provider_key'), 'oauth_accounts', ['provider'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('oauth_accounts_provider_id_key'), 'oauth_accounts', ['provider_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
